DROP TABLE IF EXISTS ROLE;
CREATE TABLE ROLE(
ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
ROLE_NAME VARCHAR(250)
);

DROP TABLE IF EXISTS UTILISATEUR;
CREATE TABLE UTILISATEUR(
USER_ID INT AUTO_INCREMENT PRIMARY KEY,
LOGIN VARCHAR(250),
USER_PASSWORD VARCHAR(250),
USER_ACTIVE INT
);

DROP TABLE IF EXISTS USER_ROLE;
CREATE TABLE USER_ROLE(
USER_ID BIGINT,
ROLE_ID BIGINT
);
